FROM golang:1.26-alpine AS builder

RUN apk add --no-cache build-base sqlite-dev \
  && mkdir -p /var/lib/sqlite

WORKDIR /go/src/github.com/ory/kratos

COPY oryx/go.mod oryx/go.mod
COPY oryx/go.sum oryx/go.sum

COPY go.mod go.mod
COPY go.sum go.sum
COPY pkg/client-go/go.* pkg/client-go/

ENV CGO_ENABLED=1
ENV CGO_CPPFLAGS=-DSQLITE_DEFAULT_FILE_PERMISSIONS=0600

RUN go mod download

COPY . .

ARG VERSION
ARG COMMIT
ARG BUILD_DATE

RUN --mount=type=cache,target=/root/.cache/go-build go build \
  -ldflags="-X 'github.com/ory/kratos/driver/config.Version=${VERSION}' -X 'github.com/ory/kratos/driver/config.Date=${BUILD_DATE}' -X 'github.com/ory/kratos/driver/config.Commit=${COMMIT}'" \
  -o /usr/bin/kratos

#########################

FROM alpine:3.21

RUN addgroup -S ory \
    && adduser -S ory -G ory -D -u 10000 -h /home/ory -s /bin/nologin \
    && apk --no-cache --update-cache --upgrade add ca-certificates sqlite-libs tzdata

WORKDIR /home/ory

COPY --from=builder /usr/bin/kratos /usr/bin/kratos

RUN mkdir -p /var/lib/sqlite \
    && chown -R ory:ory /home/ory /var/lib/sqlite

VOLUME /var/lib/sqlite
VOLUME /home/ory

EXPOSE 4433 4434

USER 10000

ENTRYPOINT ["kratos"]
CMD ["serve"]
